remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Srividhya's work in the mentorshop programme]
description: [List of all experiments and learnings]
